import type { Metadata } from "next";
import "@/styles/globals.css";
import ComponentNavbar from "@/components/navbar/navbar-component";

export const metadata: Metadata = {
  title: "LinkUp - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <ComponentNavbar />
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">{children}</div>
    </div>
  );
}
